### ISSUE TITLE
Error on Start-up

### ISSUE THREAD

**Issue by StycinViro** [asquared31415/ONI-Mods#10]
When I enable the mod and restart the game I then get a message that there was an error with my mod and it has disabled to ensure a clean restart. I've unsubbed and resubbed to it and that didn't seem to fix it.
Let me know if there's anything else I can do to fix this!

Pastebin with Log:
https://pastebin.com/R7jH7bvp

although I have other mods installed, I received the error with only this mod enabled.

**Comment by asquared31415** [comment]
That's an outdated version of the mod, the latest is version 2020.3.6.1299.  Try downloading the  [latest version](https://github.com/asquared31415/ONI-Mods/releases/download/vAutomation/MoreCanisterFillersMod.zip) and placing it in the mods folder locally.  The file structure should look something like this.

![image](https://user-images.githubusercontent.com/34665709/76169561-c72ac100-614f-11ea-8b6c-6f45cd1adce2.png)

**Comment by StycinViro** [comment]
I followed your instructions and now my game works again! Thanks!

The only thing I'll say is that I did have to create the Local folder myself because it wasn't there already, but that didn't cause any issues. And now that I have the local download for this mod I have two mods in my mod list so I'll unsub from the one via steam since it isn't working for me.

**Comment by asquared31415** [comment]
Ah yep, I forgot to mention you might need to create the folder.  Glad it worked for you.
