### ISSUE TITLE
Crashes on new automation patch

### ISSUE THREAD

**Issue by PhillipShulman** [asquared31415/ONI-Mods#11]
The new patch has broken most mods. Several people have commented on the steam workshop page that this mod crashes the game too.
After a few cycles the game pauses and cannot be unpaused, and the "error has occurred please restarts" box appears over the resources information list.
In this state, hovering over the reactor shows its information card as grey instead of blue, partially see through, with only "shinebug reactor" and no other text.

**Comment by asquared31415** [comment]
Can you please provide the output log located at `C:\Users\<USERNAME>\AppData\LocalLow\Klei\Oxygen Not Included\output_log.txt`

**Comment by PhillipShulman** [comment]
This crash happened a few days ago, and I have run the game since.  I will have to try to reproduce the crash later today

**Comment by PhillipShulman** [comment]
Ok mousing over the reactor crashed the game instantly this time:
[output_log.txt](https://github.com/asquared31415/ONI-Mods/files/4325728/output_log.txt)

**Comment by asquared31415** [comment]
This has been resolved in the latest update of the mod
