### ISSUE TITLE
Canister filter auto-drop bug

### ISSUE THREAD

**Issue by Dubroy** [asquared31415/ONI-Mods#13]
the first one is fine
when I build another Canister 
the auto-drop is not functioning for both of them

**Comment by Dubroy** [comment]
I got it wrong
the problem is that
if the gas inside the Canister is more then one type
the auto-drop may fail
it's might because the 10kg trigger of one gas is never gonna fire since there are serveral gases

**Comment by asquared31415** [comment]
This has been fixed as of the 21-04-2020 update
