### ISSUE TITLE
auto-drop bug with mixed gas

### ISSUE THREAD

**Issue by Dubroy** [asquared31415/ONI-Mods#16]
public void StorageChanged(object data)
        {
            if(!AutoDrop)
                return;

            var storage = GetComponent<Storage>();
            if(storage.RemainingCapacity() < 0.05)
                storage.DropAll();
        }
this may be the problem
it's still can't handle mixed gas

**Comment by asquared31415** [comment]
Using the current version of the mod, and the latest update of the game, both liquid and gas bottler auto dropping is working.
