### ISSUE TITLE
Rebuild/Republish Rename Asteroids

### ISSUE THREAD

**Issue by meekay** [asquared31415/ONI-Mods#16]
The Rename Asteroids mod seems to be 404'ing on Steam Workshop. At one point earlier this month a new build of ONI came out that seemed to have broken the mod, but I just forked your repo and rebuilt it locally and it seems to be working fine. So maybe it just needed a rebuild? If so, could you please republish it?

![Screen Shot 2022-03-22 at 11 28 57 AM](https://user-images.githubusercontent.com/590046/159518666-86132233-a6ae-4c29-8c2b-329d64adba41.png)

**Comment by meekay** [comment]
Alternatively, if you're not interested in maintaining it anymore, I'd be happy to take your code and publish it going forward.

**Comment by asquared31415** [comment]
Turns out Steam needed me to press a different button to properly make the mod visible again, something about a workshop agreement.  Fixed.

**Comment by meekay** [comment]
Wonderful, thank you!
