### ISSUE TITLE
ShinebugReactor - Sluggish when reactor is selected

### ISSUE THREAD

**Issue by TermanEmil** [asquared31415/ONI-Mods#18]
**Steps to reproduce:**
1. Install a ShinebugReactor
2. Dump lots of eggs (say 400 eggs)
3. Select it

It's significantly lagging. At least, for my potato.

**Possible solution:**
Don't display the eggs in contents/storage.

**Comment by asquared31415** [comment]
As you suspected, this is indeed the base game not liking to display many items.  Even on powerful computers, it will drag to a crawl.  I have some code in another mod to toggle displaying storage, I will add that to the reactor.

**Comment by asquared31415** [comment]
Addressed in f765acf
