### ISSUE TITLE
[Auto follow Cam] It starts to follow even when I am playing the game

### ISSUE THREAD

**Issue by Nipodemos** [asquared31415/ONI-Mods#19]
sometimes you start to build things or change priorities or observe your dupes doing the job without moving the camera. But the mouse is still moving, I am still playing!
But your mod start to follow a dupe disregarding this, i think it checks the camera being moved rather than the mouse being moved

So my suggestions is:
only start auto-follow-cam when the game has no mouse nor keyboard input for 30 seconds

**Comment by asquared31415** [comment]
Mitigated in 1.1.2 by not starting to follow a dupe when any tool or build preview is open

**Comment by Etrit1** [comment]
I was starting to write an issue asking to be able to adjust the idle time before Autofollow kicks in but, I guess just opening a tool will also work.

I frequently just stare at the game trying to figure something out and don't like pausing it 'cause my dupes are busy doing other important things while I figure it out.. so I guess I'll just do it this way.
