### ISSUE TITLE
Shinebug reactor drops raw egg

### ISSUE THREAD

**Issue by HuskyUnit** [asquared31415/ONI-Mods#2]
Periodically a raw egg item will drop from the reactor onto the ground. Dupes come along and pick it up to cook and eat. 

Save file: 
[Septic Tank Simulator.zip](https://github.com/asquared31415/ONI-Mods/files/3847055/Septic.Tank.Simulator.zip)

**Comment by asquared31415** [comment]
After running the save for quite a while using the latest version of the mod, I don't see that happening.  Maybe it was fixed in a recent update to the mod.

**Comment by asquared31415** [comment]
Closing as the way the mod handles this has changed.
