### ISSUE TITLE
[Micro Transformers] Only 1 outlet and in-game displays 1000W?

### ISSUE THREAD

**Issue by ShadowKitty42** [asquared31415/ONI-Mods#20]
Love the mod and I'm glad that it functions correctly. There's just a couple bugs I've found so far. The first is that it only has 1 plug interface in-game. Putting the second wire in the correct spot still works, but it should have a plug on both spots.

The other, and I'm not sure if it's just a game limitation or if it's not functioning properly, but when hovering on a circuit using this transformer, it still displays 1000W even though it should be 750W.

**Comment by asquared31415** [comment]
Fixed in version 2.0.2
