### ISSUE TITLE
Meep artworks broke D:

### ISSUE THREAD

**Issue by aki-art** [asquared31415/ONI-Mods#26]
Last update overhauled how Artables work, so Meep artworks no longer show up.
Now Artable Stages are a database entry, and each define the kanim file they pull from. Most vanilla artables now have individual kanim files as well.

Patching all ArtableStages to reference the unified kanim file again instead would work.

**Comment by asquared31415** [comment]
Art for paintings and sculptures is fixed in version 2.0.2, the monument is temporarily un-meepified

**Comment by asquared31415** [comment]
Properly resolved in 2.0.3, it was just a scaling issue it turns out.
