### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by YKSDR** [asquared31415/ONI-Mods#4]
The shinebug reactor is not producing any power. Sent in multiple eggs 98% incubation process but nothing appears. Under content appears to have nothing at all.

**Comment by Fokson** [comment]
By any chance, is the Reactor's info page _supposed_ to say "Contents: None"?  You say in the description on the workshop page "Shinebug eggs are piped into the building, where they are destroyed and simulated with no lag."  They're definitely being destroyed, but is there supposed to be some kind of indication that they made it into the machine for simulation?

**Comment by asquared31415** [comment]
This was all fixed with the recent updates to the mod.
