### ISSUE TITLE
Error occurs when building the reactor.

### ISSUE THREAD

**Issue by Fokson** [asquared31415/ONI-Mods#5]
When the reactor blueprint is placed in the world, the game pauses itself.  From there on, every time a dupe clears a natural tile ( ie dirt, sandstone ) in the blueprint's way, the game pauses again.  The log spits this out every time the game is paused:

```
[20:54:31.879] [1] [ERROR] Assert failed: validRowIndices[192] isn't big enough < 236
[20:54:31.881] [1] [INFO] Error occurred with mods active. Disabling all mods (unless dev mods active).
Assert failed: validRowIndices[192] isn't big enough < 236
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)
```

Not entirely sure if the mod that's causing the issue is yours, but it only happened when building the reactor.  As a side note, I also suffer from issue #4 , in case they're related.

**Comment by asquared31415** [comment]
Could not reproduce
