### ISSUE TITLE
Canister Fillers is outdated after recent update.

### ISSUE THREAD

**Issue by Aberro** [asquared31415/ONI-Mods#7]
As title says. If enable this mod, it gets disabled next time the game starts.

**Comment by asquared31415** [comment]
Yes, I am aware of this issue, and I have a fix for it in the works.  By
the end of tomorrow all my mods should be updated to the latest version.

**Comment by asquared31415** [comment]
The latest version of the mod should resolve this issue.  Check that it is loading version 2020.2.5.376 in the logs.  If Steam doesn't give it to you, try the version in the Releases tab.
