### ISSUE TITLE
Crash when initially selecting people

### ISSUE THREAD

**Issue by anSicht-knight** [asquared31415/ONI-Mods#9]
[output_log.txt](https://github.com/asquared31415/ONI-Mods/files/4302424/output_log.txt)

**Comment by asquared31415** [comment]
That is an outdated version of the Canister Fillers mod, please try to unsubscribe and resubscribe, but there's nothing I can do, Steam sometimes doesn't give people the right files.

**Comment by asquared31415** [comment]
Please see the instructions in #10 to update the mod locally.

**Comment by anSicht-knight** [comment]
ok,thanks

--------------原始邮件--------------
发件人："asquared31415 "<notifications@github.com&gt;;
发送时间：2020年3月9日(星期一) 凌晨3:18
收件人："asquared31415/ONI-Mods" <ONI-Mods@noreply.github.com&gt;;
抄送："anSicht-knight "<luojin@stu.haut.edu.cn&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [asquared31415/ONI-Mods] Crash when initially selecting people (#9)
-----------------------------------

 
Please see the instructions in #10 to update the mod locally.

**Comment by anSicht-knight** [comment]
Can I share this mod with my friends？ of course, I will note your id.XD
