### ISSUE TITLE
Better Multitool Animations - crash

### ISSUE THREAD

**Issue by HugePinball** [asquared31415/ONI-Mods#9]
Just had a crash in Spaced Out, public testing branch 485768.  I marked the Rover's Lander for deconstruction with the deconstruct tool and received this crash message:

ScoutRover does not have component AttributeLevels

UnityEngine.Debug:LogError (object)
Debug:LogError (object) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Debug.cs:142)
StateMachine`4/TargetParameter<MultitoolController, MultitoolController/Instance, Worker, object>:Get<Klei.AI.AttributeLevels> (MultitoolController/Instance) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1850)
BetterAnimations.BetterAnimationsPatches/MultitoolController_Patch:GetScaleHelper (single,MultitoolController/Instance)
(wrapper dynamic-method) MultitoolController/Instance:MultitoolController+Instance.PlayPre_Patch0 (MultitoolController/Instance)
MultitoolController:<InitializeStates>b__4_0 (MultitoolController/Instance) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/fx/MultitoolController.cs:28)
StateMachine`4/GenericInstance<MultitoolController, MultitoolController/Instance, Worker, object>:ExecuteActions (StateMachine`4/State<MultitoolController, MultitoolController/Instance, Worker, object>,System.Collections.Generic.List`1<StateMachine/Action>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:875)
StateMachine`4/GenericInstance<MultitoolController, MultitoolController/Instance, Worker, object>:PushState (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:834)
StateMachine`4/GenericInstance<MultitoolController, MultitoolController/Instance, Worker, object>:GoTo (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1141)
StateMachine/Instance:StartSM () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:253)
StateMachine`4/GenericInstance<MultitoolController, MultitoolController/Instance, Worker, object>:StartSM () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1010)
Worker:StartWork (Worker/StartWorkInfo) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/components/Worker.cs:426)
GameStateMachine`4/State/<>c__DisplayClass81_0`1<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object, Deconstructable>:<ToggleWork>b__0 (WorkChore`1/StatesInstance<Deconstructable>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/GameStateMachine.cs:2052)
GameStateMachine`4/State/<>c__DisplayClass80_0<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:<ToggleWork>b__0 (WorkChore`1/StatesInstance<Deconstructable>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/GameStateMachine.cs:1992)
StateMachine`4/GenericInstance<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:ExecuteActions (StateMachine`4/State<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>,System.Collections.Generic.List`1<StateMachine/Action>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:875)
StateMachine`4/GenericInstance<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:PushState (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:834)
StateMachine`4/GenericInstance<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:GoTo (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1141)
GameStateMachine`4/EventTransitionData<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:ExecuteTransition (WorkChore`1/StatesInstance<Deconstructable>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/GameStateMachine.cs:254)
GameStateMachine`4/EventTransitionData<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:OnCallback (WorkChore`1/StatesInstance<Deconstructable>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/GameStateMachine.cs:264)
GameStateMachine`4/EventTransitionData/<>c__DisplayClass7_0<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:<Register>b__0 (object) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/GameStateMachine.cs:280)
EventSystem:Trigger (UnityEngine.GameObject,int,object) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/EventSystem.cs:161)
EventExtensions:Trigger (UnityEngine.GameObject,int,object) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/EventSystem.cs:582)
GameStateMachine`4/State/<>c__DisplayClass73_0<Navigator/States, Navigator/StatesInstance, Navigator, object>:<TriggerOnEnter>b__0 (Navigator/StatesInstance) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/GameStateMachine.cs:1828)
StateMachine`4/GenericInstance<Navigator/States, Navigator/StatesInstance, Navigator, object>:ExecuteActions (StateMachine`4/State<Navigator/States, Navigator/StatesInstance, Navigator, object>,System.Collections.Generic.List`1<StateMachine/Action>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:875)
StateMachine`4/GenericInstance<Navigator/States, Navigator/StatesInstance, Navigator, object>:PushState (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:834)
StateMachine`4/GenericInstance<Navigator/States, Navigator/StatesInstance, Navigator, object>:GoTo (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1141)
Navigator:Stop (bool,bool) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/components/Navigator.cs:461)
Navigator:AdvancePath (bool) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/components/Navigator.cs:414)
Navigator:GoTo (KMonoBehaviour,CellOffset[],NavTactic) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/components/Navigator.cs:303)
GameStateMachine`4/State/<>c__DisplayClass114_0`1<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object, Deconstructable>:<MoveTo>b__0 (WorkChore`1/StatesInstance<Deconstructable>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/GameStateMachine.cs:2613)
StateMachine`4/GenericInstance<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:ExecuteActions (StateMachine`4/State<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>,System.Collections.Generic.List`1<StateMachine/Action>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:875)
StateMachine`4/GenericInstance<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:PushState (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:834)
StateMachine`4/GenericInstance<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:GoTo (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1141)
StateMachine/Instance:StartSM () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:253)
StateMachine`4/GenericInstance<WorkChore`1/States<Deconstructable>, WorkChore`1/StatesInstance<Deconstructable>, WorkChore`1<Deconstructable>, object>:StartSM () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1010)
Chore:Begin (Chore/Precondition/Context) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/demands/Chore.cs:710)
WorkChore`1<Deconstructable>:Begin (Chore/Precondition/Context) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/chores/WorkChore.cs:190)
ChoreDriver/StatesInstance:BeginChore () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/demands/ChoreDriver.cs:30)
ChoreDriver/States/<>c:<InitializeStates>b__5_2 (ChoreDriver/StatesInstance) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/demands/ChoreDriver.cs:107)
StateMachine`4/GenericInstance<ChoreDriver/States, ChoreDriver/StatesInstance, ChoreDriver, object>:ExecuteActions (StateMachine`4/State<ChoreDriver/States, ChoreDriver/StatesInstance, ChoreDriver, object>,System.Collections.Generic.List`1<StateMachine/Action>) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:875)
StateMachine`4/GenericInstance<ChoreDriver/States, ChoreDriver/StatesInstance, ChoreDriver, object>:PushState (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:834)
StateMachine`4/GenericInstance<ChoreDriver/States, ChoreDriver/StatesInstance, ChoreDriver, object>:GoTo (StateMachine/BaseState) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1141)
StateMachine`4/Parameter`1/Transition<ChoreDriver/States, ChoreDriver/StatesInstance, ChoreDriver, object, Chore>:Evaluate (ChoreDriver/StatesInstance) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1293)
StateMachine`4/Parameter`1/Context<ChoreDriver/States, ChoreDriver/StatesInstance, ChoreDriver, object, Chore>:Set (Chore,ChoreDriver/StatesInstance) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1369)
StateMachine`4/Parameter`1<ChoreDriver/States, ChoreDriver/StatesInstance, ChoreDriver, object, Chore>:Set (Chore,ChoreDriver/StatesInstance) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/statemachine/StateMachine.cs:1251)
ChoreDriver:SetChore (Chore/Precondition/Context) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/demands/ChoreDriver.cs:172)
Brain:UpdateChores () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/Brain.cs:80)
Brain:UpdateBrain () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/Brain.cs:57)
BrainScheduler/BrainGroup:RenderEveryTick (single,bool) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/BrainScheduler.cs:207)
BrainScheduler:RenderEveryTick (single) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/ai/BrainScheduler.cs:360)
SimAndRenderScheduler/RenderEveryTickUpdater:Update (IRenderEveryTick,single) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/SimAndRenderScheduler.cs:188)
UpdateBucketWithUpdater`1<IRenderEveryTick>:Update (single) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/StateMachineUpdater.cs:79)
StateMachineUpdater/BucketGroup:AdvanceOneSubTick (single) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/StateMachineUpdater.cs:152)
StateMachineUpdater:RenderEveryTick (single) (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/Plugins/Klei/util/StateMachineUpdater.cs:264)
Game:LateUpdate () (at C:/jenkins_workspace/workspace/Preview_Simgame_Windows/game/Assets/scripts/game/Game.cs:1628)

Build: U38-485768-SD

**Comment by DaftValac** [comment]
I also just ran into this error, only with digging.

**Comment by asquared31415** [comment]
Thanks for the report, this is fixed in version 2.0.2 (you may need to wait a short while for the update to become available)
